# Generated by Django 2.0 on 2021-04-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Address',
        ),
    ]
