# Generated by Django 2.0 on 2021-04-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210409_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='is_active',
            new_name='Is_active',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='is_created',
            new_name='Is_created',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='is_verified',
            new_name='Is_verified',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='firstname',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='Firstname',
        ),
    ]
