# Generated by Django 2.0 on 2021-04-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210411_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='tagline',
            field=models.CharField(default='Tagline', max_length=100),
        ),
    ]
