# Generated by Django 2.0 on 2021-04-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_artist_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='tagline',
        ),
        migrations.AddField(
            model_name='customer',
            name='tagline',
            field=models.CharField(default='Tagline', max_length=100),
        ),
    ]
