# Generated by Django 2.0 on 2021-04-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210411_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Intro',
            field=models.CharField(default='Introduce Yourself....', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tagline',
            field=models.CharField(default='Your Tagline', max_length=100),
        ),
    ]
