# Generated by Django 2.0 on 2021-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210411_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Loc',
            field=models.CharField(default='Select State', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Loc',
            field=models.CharField(default='Select State', max_length=50),
        ),
    ]
