# Generated by Django 2.0 on 2021-04-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210411_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='ProfilePic',
            field=models.ImageField(default='abc', upload_to='artist/profile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ProfilePic',
            field=models.ImageField(default='customer/profile', upload_to=''),
        ),
    ]
