# Generated by Django 2.0 on 2021-04-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210411_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Intro',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tagline',
        ),
        migrations.AddField(
            model_name='artist',
            name='Intro',
            field=models.CharField(default='Introduce Yourself....', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='tagline',
            field=models.CharField(default='Your Tagline', max_length=100),
        ),
    ]
