# Generated by Django 2.0 on 2021-04-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210418_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
