# Generated by Django 2.0 on 2021-04-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_artist_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookArtistReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Des', models.CharField(max_length=255, null=True)),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Artist')),
                ('Cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
    ]
